@Builder
declare function func(): void;
@Component
@Entry
@Entry
declare struct MyTestable {
    @Consume
    private property1;
    @Consume
    private property2;
    @Consume
    protected property3: any;
    @Consume
    protected property4: any;
    @Consume
    property5: string;
    @Consume
    property6: number;
}
declare struct index02 {
    @Styles
    method3();
}
@Entry
declare struct MainPage02 {
    @State
    message: string;
    @State
    data: any;
    Build(): void;
}
