const Rectangle = class {
  constructor(height: number, width: number) {
    this.height = height
    this.width = width
  }
  height
  width
}

const rectangle = new Rectangle(0.0, 0.0)


class Rectangle_right {
  constructor(height: number, width: number) {
    this.height = height
    this.width = width
  }

  height: number
  width: number
}

const rectangle_right = new Rectangle_right(0.0, 0.0)


export let other = 1;